Repository raphaelvallat/yasa, pull requests merged in 2022-12, with the labels that each got.

#108 Stairs plot
  docs/changelog.rst
  notebooks/03_spindles_detection_NREM_only.ipynb
  notebooks/10_spectrogram.ipynb
  notebooks/13_artifact_rejection.ipynb
  notebooks/16_EEG-HRV_coupling.ipynb
  yasa/plotting.py
  yasa/tests/test_plotting.py
  yasa/tests/test_spectral.py
Labels: enhancement :construction:

#115 Solves obscure numba bug with just replacing range -> zip
  yasa/numba.py
Labels: bug :boom:, URGENT ❗

#110 Hypno simulation
  docs/api.rst
  docs/changelog.rst
  yasa/hypno.py
  yasa/tests/test_hypno.py
Labels: enhancement :construction:

#119 Hotfix for MNE plot_topomap deprecation
  yasa/plotting.py
Labels: bug :boom:

#121 Update simulate_hypno to return Hypnogram instance
  docs/changelog.rst
  yasa/hypno.py
  yasa/tests/test_hypno.py
  yasa/tests/test_hypnoclass.py
Labels: enhancement :construction:

#123 Add FutureWarning in hypnogram functions
  docs/changelog.rst
  yasa/hypno.py
  yasa/sleepstats.py
  yasa/tests/test_hypno.py
  yasa/tests/test_hypnoclass.py
Labels: enhancement :construction:

#124 Hypnogram plot_hypnogram method
  docs/changelog.rst
  yasa/hypno.py
  yasa/plotting.py
  yasa/tests/test_hypnoclass.py
  yasa/tests/test_plotting.py
Labels: enhancement :construction:

#126 Default dtype of pandas.Series is now a categorical
  docs/changelog.rst
  yasa/hypno.py
  yasa/plotting.py
  yasa/tests/test_hypno.py
  yasa/tests/test_hypnoclass.py
  yasa/tests/test_plotting.py
Labels: enhancement :construction:

#129 Update string representation of yasa.Hypnogram
  yasa/hypno.py
Labels: enhancement :construction:
